package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLClassificationUtils",
    hdrs = [
        "sources/TFLClassificationUtils.h",
    ],
    srcs = [
        "sources/TFLClassificationUtils.m",
    ],
    deps = [
        "//tensorflow_lite_support/c/task/processor:classification_result"
    ],
    module_name = "TFLClassificationUtils",
)
