package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

py_library(
    name = "tflite_text_api",
    srcs = ["tflite_text_api.py"],
    deps = [
        "//tensorflow_lite_support/custom_ops:expect_tfpy_installed",
        "//tensorflow_lite_support/custom_ops:expect_tftext_installed",
    ],
)
