package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

py_library(
    name = "tflite_text_api",
    srcs = ["tflite_text_api.py"],
    deps = [
        "//third_party/py/tensorflow",
        "//third_party/py/tensorflow_text",
    ],
)
