package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

# We expect several libraries to already be installed on the system, e.g. via
# `pip install numpy`
py_library(
    name = "expect_numpy_installed",
)

# `pip install tensorflow`
py_library(
    name = "expect_tfpy_installed",
)

# `pip install tensorflow_text`
py_library(
    name = "expect_tftext_installed",
)
