package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLClassificationOptions",
    hdrs = [
        "Sources/TFLClassificationOptions.h",
    ],
    module_name = "TFLClassificationOptions",
)
