package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLClassificationOptions",
    hdrs = [
        "apis/TFLClassificationOptions.h",
    ],
    module_name = "TFLClassificationOptions",
)

objc_library(
    name = "TFLClassificationResult",
    hdrs = [
        "apis/TFLClassificationResult.h",
    ],
    module_name = "TFLClassificationResult",
)
