# TFLite Support is a toolkit that helps users to develop ML and deploy TFLite
# models onto mobile devices.

package(
    default_visibility = ["//visibility:private"],
    licenses = ["notice"],  # Apache 2.0
)

exports_files(["LICENSE"])

package_group(
    name = "users",
    packages = [
        "//research/kernel/softskills/...",
        "//tensorflow_lite_support/...",
    ],
)
