package(
    default_visibility = [
        "//tensorflow_lite_support:__subpackages__",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "frame_buffer",
    hdrs = [
        "frame_buffer.h",
    ],
)
