package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "frame_buffer_c_api",
    hdrs = [
        "frame_buffer.h",
    ],
)

