package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLTestUtil",
    srcs = [
        "sources/TFLTestUtils.m",
    ],
    hdrs = [
        "sources/TFLTestUtils.h",
    ],
    deps = [
        "//tensorflow_lite_support/ios/task/processor:TFLDetectionResult",
    ],
    module_name = "TFLTestUtil",
)
