package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLTestUtil",
    hdrs = [
        "sources/TFLTestUtils.h",
    ],
    module_name = "TFLTestUtil",
)
