package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "classification_result",
    srcs = [
        "classification_result.cc",
    ],
    hdrs = ["classification_result.h"],
)

cc_library(
    name = "bounding_box",
    hdrs = ["bounding_box.h"],
)

cc_library(
    name = "classification_options",
    hdrs = ["classification_options.h"],
)
