package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "classification_result_c_api",
    srcs = [
        "classification_result.cc",
    ],
    hdrs = ["classification_result.h"],
)

cc_library(
    name = "bounding_box",
    hdrs = ["bounding_box.h"],
)

