package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "test_models",
    srcs = glob([
        "*.tflite",
    ]),
)

filegroup(
    name = "test_images",
    srcs = glob([
        "*.jpg",
        "*.png",
    ]),
)
