# Placeholder for internal Python strict test compatibility macro.

package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

py_test(
    name = "audio_record_test",
    srcs = ["audio_record_test.py"],
    deps = [
        # build rule placeholder: numpy dep,
        "//tensorflow_lite_support/python/task/audio/core:audio_record",
    ],
)
