# Placeholder for internal Python strict library compatibility macro.

package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

py_library(
    name = "segmentations_pb2",
    srcs = ["segmentations_pb2.py"],
    deps = [
        "//tensorflow_lite_support/cc/task/vision/proto:segmentations_py_pb2",
    ],
)
