# Placeholder for internal Python strict library compatibility macro.

package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

py_library(
    name = "image_classifier_options_pb2",
    srcs = ["image_classifier_options_pb2.py"],
    deps = [
        "//tensorflow_lite_support/cc/task/vision/proto:image_classifier_options_py_pb2",
        "//tensorflow_lite_support/cc/task/core/proto:base_options_py_pb2"
    ],
)
