package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLBaseOptions",
    hdrs = [
        "apis/TFLBaseOptions.h",
    ],
    module_name = "TFLBaseOptions",
)
