package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLBaseOptions",
    hdrs = [
        "Sources/TFLBaseOptions.h",
    ],
    module_name = "TFLBaseOptions",
)
