package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLBaseOptions",
    hdrs = [
        "sources/TFLBaseOptions.h",
    ],
    srcs = [
        "sources/TFLBaseOptions.m",
    ],
    module_name = "TFLBaseOptions",
)
