# Test data for universal sentence encoder qa.

package(
    default_visibility = ["//tensorflow_lite_support:users"],
    licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "test_model",
    data = ["model.tflite"],
)

filegroup(
    name = "test_metadata",
    data = ["metadata.json"],
)
