package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

filegroup(
    name = "searcher_images",
    srcs = glob([
        "searcher_images/**/*.jpg",
        "searcher_images/**/*.png",
    ]),
)

filegroup(
    name = "searcher_images_metadata",
    srcs = glob([
        "searcher_images/**/*.dat",
    ]),
)
