# Description:
# TensorFlow Lite Support API in Java.

load("@build_bazel_rules_android//android:rules.bzl", "android_library")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

android_library(
    name = "tensorflow-lite-support",
    srcs = [],
    manifest = "AndroidManifest.xml",
    deps = [
        "@org_tensorflow//tensorflow/lite/java:tensorflowlite",
    ],
)
