package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "GMLImage+FileIOOperations",
    srcs = [
        "sources/GMLImage+FileIOOperations.m",
    ],
    hdrs = [
        "sources/GMLImage+FileIOOperations.h",
    ],
    module_name = "GMLImage+FileIOOperations",
    deps = [
        "//tensorflow_lite_support/odml/ios/image:MLImage",
    ],
)
