package(
    default_visibility = [
        "//tensorflow_lite_support:internal",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "audio_buffer",
    srcs = [
        "audio_buffer.c",
    ],
    hdrs = [
        "audio_buffer.h",
    ],
)
