package(
    default_visibility = ["//tensorflow_lite_support:__subpackages__"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "GMLImageUtils",
    hdrs = [
        "sources/GMLImageUtils.h",
    ],
    module_name = "GMLImageUtils",
    deps = [
        "//tensorflow_lite_support/c/task/vision/core:frame_buffer",
        "//tensorflow_lite_support/odml/ios/image:MLImage",
    ],
)
