package(
    default_visibility = ["//tensorflow_lite_support:internal"],
    licenses = ["notice"],  # Apache 2.0
)

objc_library(
    name = "TFLCommonCUtils",
    srcs = [
        "sources/TFLCommonCUtils.m",
    ],
    hdrs = [
        "sources/TFLCommonCUtils.h",
    ],
    module_name = "TFLCommonCUtils",
    deps = [
        "//tensorflow_lite_support/c:common",
        "//tensorflow_lite_support/ios/utils:TFLCommonUtils",
    ],
)
